# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


brands = [
  'AXIS',
  'Advance',
  'Aeolian',
  'Airush',
  'AlpineFoil',
  'Amundson',
  'Armstrong',
  'Axis',
  'BU Boards Unlimited',
  'BWSurf',
  'Best',
  'Blade',
  'Board Buddy',
  'Boardriding Maui',
  'Body Glove',
  'Brokite',
  'Brunotti',
  'CORE',
  'Cabrinha',
  'Camet',
  'Cannibal',
  'Carved',
  'Caution',
  'Core',
  'Crazy Foil',
  'CrazyFly',
  'Dakine',
  'Delta',
  'Dry Fashion',
  'Duotone',
  'EH',
  'Eleveight',
  'Enata',
  'Epic',
  'ExoWaters',
  'F-One',
  'F4',
  'Fanatic',
  'Firewire',
  'Flexifoil',
  'Flysurfer',
  'Go Foils',
  'GoPro',
  'Gong',
  'Groove',
  'HB Surf',
  'Henderson',
  'Horue',
  'Hyperlite',
  'ION',
  'Infinity',
  'JP',
  'Jimmy Lewis',
  'Ketos',
  'Kitech',
  'Kokatat',
  'LEN10',
  'LP Foils',
  'Levitaz',
  'Libtech',
  'Lift/MHL',
  'Liquid Force',
  'Litewave',
  'Lost',
  'Manera',
  'Mike\'s Lab',
  'Moses',
  'Mystic',
  'NP Surf',
  'NPX',
  'NRS',
  'NSI',
  'Naish',
  'Neil Pryde',
  'Nobile',
  'North',
  'O\'Neill',
  'Ocean Rodeo',
  'Other',
  'Ozone',
  'Patagonia',
  'Peter Lynn',
  'ProMotion',
  'Prolimit',
  'Pyzel',
  'Quiet Flight',
  'RRD',
  'Reedin',
  'Ride Engine',
  'Ronix',
  'Slater Designs',
  'SP Boarding',
  'Seavenger',
  'Shinn',
  'SkyWalker',
  'Slingshot',
  'Spleene',
  'Spotz',
  'Takoon',
  'Tona'
]

brands.each { |brand| Brand.create!(brand_name: brand) }